apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-otel
spec:
  containers:
  - name: ubuntu
    image: ubuntu
    command: ["/bin/bash", "-c"]
    args:
      - while true; do echo "Hello World $(date)" >> /var/log/system.log; sleep 1; done
    volumeMounts:
    - name: varlog
      mountPath: /var/log
  - name: otel-collector
    # image: ubuntu
    image: otel/opentelemetry-collector-contrib:0.72.0
    # command: ["tail", "-f", "/var/log/system.log"]
    command:
    - /otelcol-contrib
    - --config=/conf/relay.yaml
    volumeMounts:
    - mountPath: /conf
      name: opentelemetry-collector-configmap
    - name: varlog
      mountPath: /var/log
    env:
      - name: OTEL_RESOURCE_ATTRIBUTES_POD_NAME # set pod name as resource attribute for k8s metadata processor
        valueFrom:
          fieldRef:
            fieldPath: metadata.name 
  volumes:
  - name: varlog
    emptyDir: {}
  - name: opentelemetry-collector-configmap 
    configMap:
      defaultMode: 420
      items:
      - key: relay
        path: relay.yaml
      name: opentelemetry-collector
    #  - name: OTEL_CONFIG # set config file as environment variable 
    #    valueFrom:
    #      configMapKeyRef:
    #        name: opentelemetry-collector
    #        key: relay