mode: "deployment"

config:
  receivers:
    filelog:
      include: [/var/log/*.log]

  processors:
    batch: {}

  exporters:
    logging:
      loglevel: debug

    loki:
      endpoint: "http://loki.homelab.svc.cluster.local:3100/loki/api/v1/push"
      labels:
        attributes:
          log.file.name: "filename"

  service:
    pipelines:
      logs:
        receivers: [filelog]
        processors: [batch]
        exporters: [loki]
