# https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/lokiexporter/README.md

mode: "deployment"

replicaCount: 0

image:
  repository: "otel/opentelemetry-collector-contrib"

config:
  receivers:
    filelog:
      include: [/var/log/*.log]

  processors:
    attributes:
      actions:
        - action: insert
          key: log_file_name
          from_attribute: log.file.name
        - action: insert
          key: loki.attribute.labels
          value: log_file_name

  exporters:
    logging:
      loglevel: debug

    loki:
      endpoint: "http://loki-stack.homelab.svc.cluster.local:3100/loki/api/v1/push"
      default_labels_enabled:
        exporter: false
        job: true

  service:
    pipelines:
      metrics: null
      logs:
        receivers: [filelog]
        processors: [attributes]
        exporters: [loki]
