# https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/lokiexporter/README.md

mode: "deployment"

image:
  repository: "otel/opentelemetry-collector-contrib"

config:
  receivers:
    filelog:
      include: [/var/log/*.log]

  processors:
    batch: {}

  exporters:
    logging:
      loglevel: debug

    loki:
      endpoint: "http://loki-stack.homelab.svc.cluster.local:3100/loki/api/v1/push"
      default_labels_enabled:
        exporter: false
        job: true
      # labels:
      #   attributes:
      #     log.file.name: "filename"

  service:
    pipelines:
      logs:
        receivers: [filelog]
        processors: [batch]
        exporters: [loki]
