apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{"deployment.kubernetes.io/revision":"1","objectset.rio.cattle.io/applied":"H4sIAAAAAAAA/6xV0W/buA/+V37gs93EbbdmBn4Pu6Z3G7blgqXdy1AMikzHusiiTqLTBoX/9wNtJ022rtsO9xRHIqmPH/mRD6C8+YQhGnKQg/I+jjYZJLA2roAcpugtbWt0DAnUyKpQrCB/AOUcsWJDLspfWv6FmiPySTB0ohWzxRNDIyNBIPnuPd05DOlqs4Yc1mfx4GaTJf97Z1zx/9dFQe6HIZyqEXLQFLBw8afMo1dafNbNEtO4jYw1tAlYtUTbJbWexFR5vzPp48pncMgYJdrw7CUFnM4WzzxbqVhBDkuNp5Oz01eTSZZdnJ+p8dnkpVq+yMblafnyAsuL89PzsX5xIUC+SekZ0NGjFsgBN0Zq+cZEprB9b2rDkI8TiGhRMwUxqhXr6v1zabYSkoNiXG27sGStcasbXyjGPsT9jVMbZaxaWoQ8axPgrRdkH49s5Rxrb3d+By30LNHtQVKaHCvjMETIPz+ACiv5gFSTKyGBEbIeDSyNpBKlsQi3CZharQRRUE5XGEa1CUHM0sF495tnJ69OzmFwmDfWzskavYUc3pYz4nnA2CvAmg06jHEeaNnlUypjm4DXVcBYkS0gP0ugYvZ/IMu9VyxlH1WoLFeQgKfAkE/GE6mJrrAr8Zvr67kwZZxho+wUrdouUJMrIuQvxwl4DIaK/VEmzo3WGOPBy1kCbGqkhh8Nn2ojgdAzuSd23qF6cba3HiwDMWmykMPNVBD+wCVl7Y/dri+fdHuVHTjWyMHo+ITjbQIBVWH+FeXiuX1kPJtkP8v4t4Sf/gLfASM1QWPX2VYEGPvOrylIS2UX4w8GOsO/G4z9rfaNXI3HdTdnB9PeUpSAugmGt5fkGO+7NJW1dDcPZmMsrvAqamW7cQx5qWzEBLTyammsYdNDUUUhqpldXX/57e1s+mVx9fHT28srEUoRyMudshZu2570P53dfiTi343FYc7kHBpsE9iQbWr8QI0b+qiWz/nA+4Ea4aD7XGlWae8Jjy/sYn4/xkg3kak+CNX9T38Q8Vaap3Bxr+QplqqxImJHBS4OxuESWZ0cj3WKkIM1rrmXQvlgqGPfqhhnPYqeklTbJjKGVAfDRisLUquwMRpfay0Zzb5WH5PFsFucnx9gjYLucvDvll3s8kiAvFgKSLi6N9IpQhSWJWqGHGa00BUWjZX0+zCSWhrI4lf5iPwC2dRb5fA/jVwryf/pkLeSrSdLq+3CS30uyclWMbu+6TbA4pc3U63uF2u86xU4PPCuQ3mMraLIXdMkcFehu3FRsYml6VcWTGlGvE9U0PbNtJ+NpVl9UF6AGMb6qFy7LZPsxs3+RIjsjWZU4BsSJvZWj0fy3FeTuf2OWob5+Yjm2C/dC4S8tJWye6E+p5j2tm3b9p8AAAD//+Um+xUACgAA","objectset.rio.cattle.io/id":"","objectset.rio.cattle.io/owner-gvk":"k3s.cattle.io/v1, Kind=Addon","objectset.rio.cattle.io/owner-name":"coredns","objectset.rio.cattle.io/owner-namespace":"kube-system"},"creationTimestamp":"2023-06-25T17:32:23Z","generation":1,"labels":{"k8s-app":"kube-dns","kubernetes.io/name":"CoreDNS","objectset.rio.cattle.io/hash":"bce283298811743a0386ab510f2f67ef74240c57"},"name":"coredns","namespace":"kube-system","resourceVersion":"25024753","uid":"70564610-dcf6-48df-85cd-f6b93213c6bd"},"spec":{"progressDeadlineSeconds":600,"replicas":1,"revisionHistoryLimit":0,"selector":{"matchLabels":{"k8s-app":"kube-dns"}},"strategy":{"rollingUpdate":{"maxSurge":"25%","maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"k8s-app":"kube-dns"}},"spec":{"containers":[{"args":["-conf","/etc/coredns/Corefile"],"image":"rancher/mirrored-coredns-coredns:1.9.4","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":8080,"scheme":"HTTP"},"initialDelaySeconds":60,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"name":"coredns","ports":[{"containerPort":53,"name":"dns","protocol":"UDP"},{"containerPort":53,"name":"dns-tcp","protocol":"TCP"},{"containerPort":9153,"name":"metrics","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/ready","port":8181,"scheme":"HTTP"},"periodSeconds":2,"successThreshold":1,"timeoutSeconds":1},"resources":{"limits":{"memory":"170Mi"},"requests":{"cpu":"100m","memory":"70Mi"}},"securityContext":{"allowPrivilegeEscalation":false,"capabilities":{"add":["NET_BIND_SERVICE"],"drop":["all"]},"readOnlyRootFilesystem":true},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/etc/coredns","name":"config-volume","readOnly":true},{"mountPath":"/etc/coredns/custom","name":"custom-config-volume","readOnly":true}]}],"dnsPolicy":"Default","nodeSelector":{"beta.kubernetes.io/os":"linux"},"priorityClassName":"system-cluster-critical","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"coredns","serviceAccountName":"coredns","terminationGracePeriodSeconds":30,"tolerations":[{"key":"CriticalAddonsOnly","operator":"Exists"},{"effect":"NoSchedule","key":"node-role.kubernetes.io/control-plane","operator":"Exists"},{"effect":"NoSchedule","key":"node-role.kubernetes.io/master","operator":"Exists"}],"topologySpreadConstraints":[{"labelSelector":{"matchLabels":{"k8s-app":"kube-dns"}},"maxSkew":1,"topologyKey":"kubernetes.io/hostname","whenUnsatisfiable":"DoNotSchedule"}],"volumes":[{"configMap":{"defaultMode":420,"items":[{"key":"Corefile","path":"Corefile"},{"key":"NodeHosts","path":"NodeHosts"}],"name":"coredns"},"name":"config-volume"},{"configMap":{"defaultMode":420,"name":"coredns-custom","optional":true},"name":"custom-config-volume"}]}}},"status":{"conditions":[{"lastTransitionTime":"2023-06-25T17:32:36Z","lastUpdateTime":"2023-06-25T17:32:36Z","message":"Deployment has minimum availability.","reason":"MinimumReplicasAvailable","status":"True","type":"Available"},{"lastTransitionTime":"2023-06-25T17:32:36Z","lastUpdateTime":"2023-06-25T17:33:05Z","message":"ReplicaSet \"coredns-597584b69b\" has successfully progressed.","reason":"NewReplicaSetAvailable","status":"True","type":"Progressing"}],"observedGeneration":1,"replicas":1,"unavailableReplicas":1,"updatedReplicas":1}}
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/6xV0W/buA/+V37gs93EbbdmBn4Pu6Z3G7blgqXdy1AMikzHusiiTqLTBoX/9wNtJ022rtsO9xRHIqmPH/mRD6C8+YQhGnKQg/I+jjYZJLA2roAcpugtbWt0DAnUyKpQrCB/AOUcsWJDLspfWv6FmiPySTB0ohWzxRNDIyNBIPnuPd05DOlqs4Yc1mfx4GaTJf97Z1zx/9dFQe6HIZyqEXLQFLBw8afMo1dafNbNEtO4jYw1tAlYtUTbJbWexFR5vzPp48pncMgYJdrw7CUFnM4WzzxbqVhBDkuNp5Oz01eTSZZdnJ+p8dnkpVq+yMblafnyAsuL89PzsX5xIUC+SekZ0NGjFsgBN0Zq+cZEprB9b2rDkI8TiGhRMwUxqhXr6v1zabYSkoNiXG27sGStcasbXyjGPsT9jVMbZaxaWoQ8axPgrRdkH49s5Rxrb3d+By30LNHtQVKaHCvjMETIPz+ACiv5gFSTKyGBEbIeDSyNpBKlsQi3CZharQRRUE5XGEa1CUHM0sF495tnJ69OzmFwmDfWzskavYUc3pYz4nnA2CvAmg06jHEeaNnlUypjm4DXVcBYkS0gP0ugYvZ/IMu9VyxlH1WoLFeQgKfAkE/GE6mJrrAr8Zvr67kwZZxho+wUrdouUJMrIuQvxwl4DIaK/VEmzo3WGOPBy1kCbGqkhh8Nn2ojgdAzuSd23qF6cba3HiwDMWmykMPNVBD+wCVl7Y/dri+fdHuVHTjWyMHo+ITjbQIBVWH+FeXiuX1kPJtkP8v4t4Sf/gLfASM1QWPX2VYEGPvOrylIS2UX4w8GOsO/G4z9rfaNXI3HdTdnB9PeUpSAugmGt5fkGO+7NJW1dDcPZmMsrvAqamW7cQx5qWzEBLTyammsYdNDUUUhqpldXX/57e1s+mVx9fHT28srEUoRyMudshZu2570P53dfiTi343FYc7kHBpsE9iQbWr8QI0b+qiWz/nA+4Ea4aD7XGlWae8Jjy/sYn4/xkg3kak+CNX9T38Q8Vaap3Bxr+QplqqxImJHBS4OxuESWZ0cj3WKkIM1rrmXQvlgqGPfqhhnPYqeklTbJjKGVAfDRisLUquwMRpfay0Zzb5WH5PFsFucnx9gjYLucvDvll3s8kiAvFgKSLi6N9IpQhSWJWqGHGa00BUWjZX0+zCSWhrI4lf5iPwC2dRb5fA/jVwryf/pkLeSrSdLq+3CS30uyclWMbu+6TbA4pc3U63uF2u86xU4PPCuQ3mMraLIXdMkcFehu3FRsYml6VcWTGlGvE9U0PbNtJ+NpVl9UF6AGMb6qFy7LZPsxs3+RIjsjWZU4BsSJvZWj0fy3FeTuf2OWob5+Yjm2C/dC4S8tJWye6E+p5j2tm3b9p8AAAD//+Um+xUACgAA
    objectset.rio.cattle.io/id: ""
    objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
    objectset.rio.cattle.io/owner-name: coredns
    objectset.rio.cattle.io/owner-namespace: kube-system
  creationTimestamp: "2023-06-25T17:32:23Z"
  generation: 2
  labels:
    k8s-app: kube-dns
    kubernetes.io/name: CoreDNS
    objectset.rio.cattle.io/hash: bce283298811743a0386ab510f2f67ef74240c57
  name: coredns
  namespace: kube-system
  resourceVersion: "25065017"
  uid: 70564610-dcf6-48df-85cd-f6b93213c6bd
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      k8s-app: kube-dns
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: kube-dns
    spec:
      containers:
      - args:
        - -conf
        - /etc/coredns/Corefile
        image: rancher/mirrored-coredns-coredns:1.9.4
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: coredns
        ports:
        - containerPort: 53
          name: dns
          protocol: UDP
        - containerPort: 53
          name: dns-tcp
          protocol: TCP
        - containerPort: 9153
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /ready
            port: 8181
            scheme: HTTP
          periodSeconds: 2
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 170Mi
          requests:
            cpu: 100m
            memory: 70Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - all
          readOnlyRootFilesystem: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/coredns
          name: config-volume
          readOnly: true
        - mountPath: /etc/coredns/custom
          name: custom-config-volume
          readOnly: true
      dnsPolicy: Default
      nodeSelector:
        beta.kubernetes.io/os: linux
        kubernetes.io/hostname: pi
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: coredns
      serviceAccountName: coredns
      terminationGracePeriodSeconds: 30
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      topologySpreadConstraints:
      - labelSelector:
          matchLabels:
            k8s-app: kube-dns
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: Corefile
            path: Corefile
          - key: NodeHosts
            path: NodeHosts
          name: coredns
        name: config-volume
      - configMap:
          defaultMode: 420
          name: coredns-custom
          optional: true
        name: custom-config-volume
status:
  conditions:
  - lastTransitionTime: "2023-06-25T17:32:36Z"
    lastUpdateTime: "2023-06-25T17:32:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2023-06-25T17:32:36Z"
    lastUpdateTime: "2023-06-25T17:33:05Z"
    message: ReplicaSet "coredns-597584b69b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
