apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: affine-config
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.affine.configStorage }}
  storageClassName: openebs-hostpath
