apiVersion: v1
kind: Service
metadata:
  name: affine-postgres
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: affine-postgres
  ports:
    - port: 5432
      targetPort: 5432
