apiVersion: v1
kind: Service
metadata:
  name: affine-redis
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: affine-redis
  ports:
    - port: 6379
      targetPort: 6379
