apiVersion: v1
kind: Service
metadata:
  name: affine
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: affine
  ports:
    - name: http
      port: 3010
      targetPort: http
