name: 'ci'

on:
  pull_request:
    branches:
    - develop
    - main
  push:
    branches:
    - develop
    - main
    - 'release/**'
    - 'hotfix/**'

jobs:
  ci:
    name: ci
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform 
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7

    - name: Setup node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.17.1

    - name: Install deps
      run: npm ci

    - name: Run tests
      run: npm t