name: ci

on:
  pull_request:
    branches:
      - main
    paths:
      - 'molecules/cluster-resources/**'

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: $(cat .terraform-version)

      - uses: debianmaster/actions-k3s@master
        id: k3s
        with:
          version: v1.27.1-k3s1

      - name: Check K3s Cluster Status
        run: kubectl get nodes

      - name: Check K3s Cluster Status
        env: 
          KUBECONFIG_PATH: ${{ steps.k3s.outputs.kubeconfig }}
        run: cat ${KUBECONFIG_PATH} 
        
      - name: Terraform Init
        working-directory: molecules/cluster-resources
        run: terraform init

      - uses: nick-fields/retry@v2
        name: Terraform Apply
        env:
          TF_VAR_cluster: ${{ format('{{ name = "default", config_path = "{0}", host = "https://127.0.0.1:6443", hosts = [ "127.0.0.1.nip.io"] }}', steps.k3s.outputs.kubeconfig) }}
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: cd molecules/cluster-resources; terraform apply -auto-approve

